/**
 * scan-images.mjs
 * Scans public/images/{about,gallery,products/*} at build time and writes
 * src/data/site-images.ts so components can import static image lists.
 *
 * Run automatically via "prebuild" / "predev" npm hooks.
 */

import { readdirSync, writeFileSync, existsSync } from 'fs'
import { join, extname, dirname } from 'path'
import { fileURLToPath } from 'url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const root      = join(__dirname, '..')
const publicDir = join(root, 'public', 'images')
const outFile   = join(root, 'src', 'data', 'site-images.ts')

// Read basePath from next.config.mjs so generated URLs match the deployed site.
// With basePath='/lumos-paola', public files are served at /lumos-paola/images/...
import nextConfig from '../next.config.mjs'
const BASE_PATH = (nextConfig.basePath ?? '').replace(/\/$/, '')

const IMAGE_EXTS = new Set(['.jpg', '.jpeg', '.png', '.webp', '.gif', '.avif'])

/** Returns sorted list of image paths prefixed with basePath (e.g. /lumos-paola/images/...) */
function scanFolder(folder) {
  const dir = join(publicDir, folder)
  if (!existsSync(dir)) return []
  return readdirSync(dir)
    .filter((f) => IMAGE_EXTS.has(extname(f).toLowerCase()))
    .sort()
    .map((f) => `${BASE_PATH}/images/${folder}/${f}`)
}

/** Scans one level of subfolders inside a parent folder (e.g. products/rosas/) */
function scanSubfolders(parent) {
  const dir = join(publicDir, parent)
  if (!existsSync(dir)) return {}
  const result = {}
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    if (entry.isDirectory()) {
      const imgs = scanFolder(`${parent}/${entry.name}`)
      if (imgs.length > 0) result[entry.name] = imgs
    }
  }
  return result
}

const about    = scanFolder('about')
const gallery  = scanFolder('gallery')
const products = scanSubfolders('products')

const ts = `// AUTO-GENERATED by scripts/scan-images.mjs — do not edit manually
// Re-generated on every \`npm run build\` and \`npm run dev\`

export const ABOUT_IMAGES: string[] = ${JSON.stringify(about, null, 2)}

export const GALLERY_IMAGES: string[] = ${JSON.stringify(gallery, null, 2)}

export const PRODUCT_IMAGES: Record<string, string[]> = ${JSON.stringify(products, null, 2)}
`

writeFileSync(outFile, ts, 'utf-8')

console.log(`[scan-images] about: ${about.length} | gallery: ${gallery.length} | products: ${Object.keys(products).length} folders`)
