// AUTO-GENERATED by scripts/scan-images.mjs — do not edit manually
// Re-generated on every `npm run build` and `npm run dev`

export const ABOUT_IMAGES: string[] = []

export const GALLERY_IMAGES: string[] = []

export const PRODUCT_IMAGES: Record<string, string[]> = {}
